import { Theme } from "theme.slint";

export component InstalledTab inherits Rectangle {
    vertical-stretch: 1;
    VerticalLayout {
        alignment: center;
        spacing: 12px;
        Text {
            text: "Installed Apps - Not implemented yet";
            color: Theme.overlay1;
            font-size: 20px;
            font-weight: 700;
            horizontal-alignment: center;
        }
    }
}
