export global Theme {
    out property <color> base: #1e1e2e;
    out property <color> mantle: #181825;
    out property <color> crust: #11111b;
    
    out property <color> text: #cdd6f4;
    out property <color> subtext1: #bac2de;
    out property <color> subtext0: #a6adc8;
    out property <color> overlay1: #7f849c;
    out property <color> overlay0: #6c7086;
    
    out property <color> surface2: #585b70;
    out property <color> surface1: #45475a;
    out property <color> surface0: #313244;
    
    out property <color> red: #f38ba8;
    out property <color> green: #a6e3a1;
    out property <color> mauve: #cba6f7;
    out property <color> pink: #f5c2e7;
    out property <color> blue: #89b4fa;
    
    out property <[color]> accents: [
        #89b4fa, #cba6f7, #74c7ec, #b4befe, #94e2d5, #a6e3a1, #f9e2af, #fab387,
        #eba0ac, #f38ba8, #f2cdcd, #f5c2e7, #89dceb, #f5e0dc
    ];
}
